CREATE TABLE IF NOT EXISTS quiz (
    id INTEGER PRIMARY KEY,
    prompt VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS category {
    id INTEGER PRIMARY KEY,
    name VARCHAR(255)
}



CREATE TABLE IF NOT EXISTS quiz_question {
    id INTEGER PRIMARY KEY,
    question VARCHAR(255),
}

CREATE TABLE IF NOT EXISTS quiz_question_answer {
    id INTEGER PRIMARY KEY,
    answer VARCHAR(255)
}